version: "3"

services:
  mem:
      image: "redis:6-alpine"
      container_name: merebase-mem
      restart: always
      expose:
        - "6379"
  database:
    image: "postgres:14-alpine"
    container_name: immernote-database
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - default
      - postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: immernote-pdadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - default
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
  smtp:
    image: "mailhog/mailhog:latest"
    container_name: immernote-smtp
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev.api
    container_name: immernote-api
    restart: always
    environment:
      - IS_DEV=true
      - COOKIE_SECRET
      - COOKIE_SECURE
      - COOKIE_HOST
      - WEB_HOST
      - PGHOST
      - PGUSER
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT
      - DATABASE_URL
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SECURE
      - PORT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - ROOT_EMAIL
    volumes:
      - ./apps/api:/app/apps/api
      - ./internal:/app/internal
      - ./db:/app/db
    command: bash -c "air -c .air.toml"
    ports:
      - 4000:4000
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev.web
    container_name: immernote-web
    restart: always
    environment:
      - NODE_ENV
      - VITE_WS_HOST
    volumes:
      - "./apps/web:/app/apps/web"
    command: "pnpm --filter web dev"
    ports:
      - 3000:3000
networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
  pgadmin: