FROM golang:1.18-alpine AS base

RUN apk --no-cache add curl bash
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
	&& chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air
RUN curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64 && chmod +x /usr/local/bin/dbmate

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .