// Code generated by sqlc. DO NOT EDIT.
// source: blocks.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const listPageBlocksBySpaceHandle = `-- name: ListPageBlocksBySpaceHandle :many
SELECT
  id, type, rank, content, format, parent_block_id, parent_page_id, space_id, created_by, modified_by, created_at, modified_at, deleted_at
FROM
  public.blocks b
WHERE
  b.type = 'page'
  AND b.space_id = (
    SELECT
      s.id
    FROM
      public.spaces s
    WHERE
      s.handle = $1)
  AND b.parent_page_id = NULL
`

func (q *Queries) ListPageBlocksBySpaceHandle(ctx context.Context, handle string) ([]Block, error) {
	rows, err := q.db.Query(ctx, listPageBlocksBySpaceHandle, handle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Rank,
			&i.Content,
			&i.Format,
			&i.ParentBlockID,
			&i.ParentPageID,
			&i.SpaceID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageBlocksBySpaceID = `-- name: ListPageBlocksBySpaceID :many
SELECT
  id, type, rank, content, format, parent_block_id, parent_page_id, space_id, created_by, modified_by, created_at, modified_at, deleted_at
FROM
  public.blocks b
WHERE
  b.type = 'page'
  AND b.space_id = $1
  AND b.parent_page_id = NULL
`

func (q *Queries) ListPageBlocksBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]Block, error) {
	rows, err := q.db.Query(ctx, listPageBlocksBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Rank,
			&i.Content,
			&i.Format,
			&i.ParentBlockID,
			&i.ParentPageID,
			&i.SpaceID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
