// Code generated by sqlc. DO NOT EDIT.
// source: block_edges.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createBlockEdge = `-- name: CreateBlockEdge :exec
INSERT INTO public.block_edges ("parent_id", "block_id")
  VALUES ($1, $2)
`

type CreateBlockEdgeParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	BlockID  uuid.UUID `json:"block_id"`
}

func (q *Queries) CreateBlockEdge(ctx context.Context, arg CreateBlockEdgeParams) error {
	_, err := q.db.Exec(ctx, createBlockEdge, arg.ParentID, arg.BlockID)
	return err
}
