// Code generated by sqlc. DO NOT EDIT.
// source: blocks.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/immernote/immernote/internal/types"
	"github.com/jackc/pgtype"
)

const createPageBlock = `-- name: CreatePageBlock :one
INSERT INTO public.blocks ("id", "type", "rank", "content", "format", "parent_block_id", "parent_page_id", "space_id", "created_by", "modified_by")
  VALUES ($1, 'page', (
      SELECT
        -- Pages are by default inserted at the end
        -- Start at 1, in case we have to move the page to first position
        (COUNT(*) + 1)::text
      FROM
        public.blocks b
      WHERE
        b.space_id = $2
        -- Avoid comparing NULL
        AND (
          CASE WHEN $3::uuid IS NULL THEN
            b.parent_page_id IS NULL
          ELSE
            b.parent_page_id = $3::uuid
          END)),
      $4,
      $5,
      $6,
      $3,
      $2,
      $7,
      $7)
RETURNING
  id, type, rank, content, format, parent_block_id, parent_page_id, space_id, created_by, modified_by, created_at, modified_at, deleted_at
`

type CreatePageBlockParams struct {
	ID            uuid.UUID   `json:"id"`
	SpaceID       uuid.UUID   `json:"space_id"`
	ParentPageID  pgtype.UUID `json:"parent_page_id"`
	Content       types.Map   `json:"content"`
	Format        types.Map   `json:"format"`
	ParentBlockID pgtype.UUID `json:"parent_block_id"`
	CreatedBy     uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreatePageBlock(ctx context.Context, arg CreatePageBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, createPageBlock,
		arg.ID,
		arg.SpaceID,
		arg.ParentPageID,
		arg.Content,
		arg.Format,
		arg.ParentBlockID,
		arg.CreatedBy,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Rank,
		&i.Content,
		&i.Format,
		&i.ParentBlockID,
		&i.ParentPageID,
		&i.SpaceID,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBlocksByTypeSpaceHandleNullParentPageID = `-- name: ListBlocksByTypeSpaceHandleNullParentPageID :many
SELECT
  id, type, rank, content, format, parent_block_id, parent_page_id, space_id, created_by, modified_by, created_at, modified_at, deleted_at
FROM
  public.blocks b
WHERE (
  CASE WHEN nullif ($1::text, '') IS NOT NULL THEN
    b.type = $1::text
  ELSE
    TRUE
  END)
  AND b.space_id = (
    SELECT
      s.id
    FROM
      public.spaces s
    WHERE
      s.handle = $2)
  AND b.parent_page_id IS NULL
`

type ListBlocksByTypeSpaceHandleNullParentPageIDParams struct {
	Type        string `json:"type"`
	SpaceHandle string `json:"space_handle"`
}

func (q *Queries) ListBlocksByTypeSpaceHandleNullParentPageID(ctx context.Context, arg ListBlocksByTypeSpaceHandleNullParentPageIDParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocksByTypeSpaceHandleNullParentPageID, arg.Type, arg.SpaceHandle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Rank,
			&i.Content,
			&i.Format,
			&i.ParentBlockID,
			&i.ParentPageID,
			&i.SpaceID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByTypeSpaceHandleParentPageID = `-- name: ListBlocksByTypeSpaceHandleParentPageID :many
SELECT
  id, type, rank, content, format, parent_block_id, parent_page_id, space_id, created_by, modified_by, created_at, modified_at, deleted_at
FROM
  public.blocks b
WHERE (
  CASE WHEN nullif ($1::text, '') IS NOT NULL THEN
    b.type = $1::text
  ELSE
    TRUE
  END)
  AND b.space_id = (
    SELECT
      s.id
    FROM
      public.spaces s
    WHERE
      s.handle = $2)
  AND b.parent_page_id = $3
`

type ListBlocksByTypeSpaceHandleParentPageIDParams struct {
	Type         string      `json:"type"`
	SpaceHandle  string      `json:"space_handle"`
	ParentPageID pgtype.UUID `json:"parent_page_id"`
}

func (q *Queries) ListBlocksByTypeSpaceHandleParentPageID(ctx context.Context, arg ListBlocksByTypeSpaceHandleParentPageIDParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocksByTypeSpaceHandleParentPageID, arg.Type, arg.SpaceHandle, arg.ParentPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Rank,
			&i.Content,
			&i.Format,
			&i.ParentBlockID,
			&i.ParentPageID,
			&i.SpaceID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByTypeSpaceIDNullParentPageID = `-- name: ListBlocksByTypeSpaceIDNullParentPageID :many
SELECT
  id, type, rank, content, format, parent_block_id, parent_page_id, space_id, created_by, modified_by, created_at, modified_at, deleted_at
FROM
  public.blocks b
WHERE (
  CASE WHEN nullif ($1::text, '') IS NOT NULL THEN
    b.type = $1::text
  ELSE
    TRUE
  END)
  AND b.space_id = $2
  AND b.parent_page_id IS NULL
`

type ListBlocksByTypeSpaceIDNullParentPageIDParams struct {
	Type    string    `json:"type"`
	SpaceID uuid.UUID `json:"space_id"`
}

func (q *Queries) ListBlocksByTypeSpaceIDNullParentPageID(ctx context.Context, arg ListBlocksByTypeSpaceIDNullParentPageIDParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocksByTypeSpaceIDNullParentPageID, arg.Type, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Rank,
			&i.Content,
			&i.Format,
			&i.ParentBlockID,
			&i.ParentPageID,
			&i.SpaceID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByTypeSpaceIDParentPageID = `-- name: ListBlocksByTypeSpaceIDParentPageID :many
SELECT
  id, type, rank, content, format, parent_block_id, parent_page_id, space_id, created_by, modified_by, created_at, modified_at, deleted_at
FROM
  public.blocks b
WHERE (
  CASE WHEN nullif ($1::text, '') IS NOT NULL THEN
    b.type = $1::text
  ELSE
    TRUE
  END)
  AND b.space_id = $2
  AND b.parent_page_id = $3
`

type ListBlocksByTypeSpaceIDParentPageIDParams struct {
	Type         string      `json:"type"`
	SpaceID      uuid.UUID   `json:"space_id"`
	ParentPageID pgtype.UUID `json:"parent_page_id"`
}

func (q *Queries) ListBlocksByTypeSpaceIDParentPageID(ctx context.Context, arg ListBlocksByTypeSpaceIDParentPageIDParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocksByTypeSpaceIDParentPageID, arg.Type, arg.SpaceID, arg.ParentPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Rank,
			&i.Content,
			&i.Format,
			&i.ParentBlockID,
			&i.ParentPageID,
			&i.SpaceID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
