// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/immernote/immernote/internal/types"
	"github.com/jackc/pgtype"
)

type BlockAccessLevel string

const (
	BlockAccessLevelREADONLY    BlockAccessLevel = "READ_ONLY"
	BlockAccessLevelREADCOMMENT BlockAccessLevel = "READ_COMMENT"
	BlockAccessLevelREADWRITE   BlockAccessLevel = "READ_WRITE"
	BlockAccessLevelADMIN       BlockAccessLevel = "ADMIN"
)

func (e *BlockAccessLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BlockAccessLevel(s)
	case string:
		*e = BlockAccessLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for BlockAccessLevel: %T", src)
	}
	return nil
}

type MemberType string

const (
	MemberTypeBOT    MemberType = "BOT"
	MemberTypeGUEST  MemberType = "GUEST"
	MemberTypeMEMBER MemberType = "MEMBER"
	MemberTypeADMIN  MemberType = "ADMIN"
)

func (e *MemberType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberType(s)
	case string:
		*e = MemberType(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberType: %T", src)
	}
	return nil
}

type Block struct {
	ID            uuid.UUID    `json:"id"`
	Type          string       `json:"type"`
	Rank          string       `json:"rank"`
	Content       string       `json:"content"`
	Format        string       `json:"format"`
	ParentBlockID pgtype.UUID  `json:"parentBlockID"`
	ParentPageID  pgtype.UUID  `json:"parentPageID"`
	SpaceID       uuid.UUID    `json:"spaceID"`
	CreatedBy     uuid.UUID    `json:"createdBy"`
	ModifiedBy    uuid.UUID    `json:"modifiedBy"`
	CreatedAt     time.Time    `json:"createdAt"`
	ModifiedAt    time.Time    `json:"modifiedAt"`
	DeletedAt     sql.NullTime `json:"deletedAt"`
}

type InstanceSetting struct {
	SettingKey   string       `json:"settingKey"`
	SettingValue string       `json:"settingValue"`
	CreatedAt    time.Time    `json:"createdAt"`
	ModifiedAt   time.Time    `json:"modifiedAt"`
	DeletedAt    sql.NullTime `json:"deletedAt"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type Space struct {
	ID              uuid.UUID           `json:"id"`
	Handle          string              `json:"handle"`
	Name            string              `json:"name"`
	Icon            types.SpaceIcon     `json:"icon"`
	Settings        types.SpaceSettings `json:"settings"`
	Domains         []string            `json:"domains"`
	InvitationToken pgtype.Text         `json:"invitationToken"`
	CreatedAt       time.Time           `json:"createdAt"`
	ModifiedAt      time.Time           `json:"modifiedAt"`
	DeletedAt       sql.NullTime        `json:"deletedAt"`
}

type SpaceMember struct {
	UserID     uuid.UUID    `json:"userID"`
	SpaceID    uuid.UUID    `json:"spaceID"`
	Type       MemberType   `json:"type"`
	CreatedAt  time.Time    `json:"createdAt"`
	ModifiedAt time.Time    `json:"modifiedAt"`
	DeletedAt  sql.NullTime `json:"deletedAt"`
}

type SpacePermission struct {
	SpaceID     uuid.UUID        `json:"spaceID"`
	BlockID     uuid.UUID        `json:"blockID"`
	AccessLevel BlockAccessLevel `json:"accessLevel"`
	CreatedAt   time.Time        `json:"createdAt"`
	ModifiedAt  time.Time        `json:"modifiedAt"`
	DeletedAt   sql.NullTime     `json:"deletedAt"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	Name               string             `json:"name"`
	Avatar             string             `json:"avatar"`
	Settings           types.UserSettings `json:"settings"`
	ConfirmationToken  pgtype.Text        `json:"confirmationToken"`
	ConfirmationSentAt sql.NullTime       `json:"confirmationSentAt"`
	InvitedAt          sql.NullTime       `json:"invitedAt"`
	ConfirmedAt        sql.NullTime       `json:"confirmedAt"`
	CreatedAt          time.Time          `json:"createdAt"`
	ModifiedAt         time.Time          `json:"modifiedAt"`
	DeletedAt          sql.NullTime       `json:"deletedAt"`
}

type UserGroup struct {
	ID         uuid.UUID    `json:"id"`
	Name       string       `json:"name"`
	Icon       string       `json:"icon"`
	SpaceID    uuid.UUID    `json:"spaceID"`
	CreatedAt  time.Time    `json:"createdAt"`
	ModifiedAt time.Time    `json:"modifiedAt"`
	DeletedAt  sql.NullTime `json:"deletedAt"`
}

type UserGroupMember struct {
	UserID      uuid.UUID    `json:"userID"`
	UserGroupID uuid.UUID    `json:"userGroupID"`
	CreatedAt   time.Time    `json:"createdAt"`
	ModifiedAt  time.Time    `json:"modifiedAt"`
	DeletedAt   sql.NullTime `json:"deletedAt"`
}

type UserGroupPermission struct {
	UserGroupID uuid.UUID        `json:"userGroupID"`
	BlockID     uuid.UUID        `json:"blockID"`
	AccessLevel BlockAccessLevel `json:"accessLevel"`
	CreatedAt   time.Time        `json:"createdAt"`
	ModifiedAt  time.Time        `json:"modifiedAt"`
	DeletedAt   sql.NullTime     `json:"deletedAt"`
}

type UserPermission struct {
	UserID      uuid.UUID        `json:"userID"`
	BlockID     uuid.UUID        `json:"blockID"`
	AccessLevel BlockAccessLevel `json:"accessLevel"`
	CreatedAt   time.Time        `json:"createdAt"`
	ModifiedAt  time.Time        `json:"modifiedAt"`
	DeletedAt   sql.NullTime     `json:"deletedAt"`
}
