// Code generated by sqlc. DO NOT EDIT.
// source: page_sets.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createPageSet = `-- name: CreatePageSet :exec
INSERT INTO public.page_sets ("root_id", "page_id", "lft", "rgt")
  VALUES ($1, $2, $3, $4)
`

type CreatePageSetParams struct {
	RootID uuid.UUID `json:"root_id"`
	PageID uuid.UUID `json:"page_id"`
	Lft    int32     `json:"lft"`
	Rgt    int32     `json:"rgt"`
}

func (q *Queries) CreatePageSet(ctx context.Context, arg CreatePageSetParams) error {
	_, err := q.db.Exec(ctx, createPageSet,
		arg.RootID,
		arg.PageID,
		arg.Lft,
		arg.Rgt,
	)
	return err
}
