// Code generated by sqlc. DO NOT EDIT.
// source: page_blocks.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createPageBlock = `-- name: CreatePageBlock :exec
INSERT INTO public.page_blocks ("page_id", "block_id")
  VALUES ($1, $2)
`

type CreatePageBlockParams struct {
	PageID  uuid.UUID `json:"page_id"`
	BlockID uuid.UUID `json:"block_id"`
}

func (q *Queries) CreatePageBlock(ctx context.Context, arg CreatePageBlockParams) error {
	_, err := q.db.Exec(ctx, createPageBlock, arg.PageID, arg.BlockID)
	return err
}
